### ISSUE TITLE
[UI]: Application table of contents with multiple icon states

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#15]
**Goal:** To build the table of contents component for the application. 

Something similar has been done in the platform, so have a look at this:
1. Vertical tabs: https://argo-ui-storybook.netlify.app/?path=/story/uikit-verticaltabs--basic
2. This version of the tabs has the last item disabled, like we will need for the table of contents:
https://argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-clinicaltimeline--basic

**Note about icons:** There's an icon library in storybook you can utilize throughout this Epic. I'm not sure if this is being kept up to date? https://argo-ui-storybook.netlify.app/?path=/story/uikit-icon--all-icons

Zeplin: https://zpl.io/2y3AnAy

## Expected Outcomes
- [x] 1. Default tab state
- [x] 2. Hover tab state
- [x] 3. Active tab state
- [x] 4. Ability to add different icons as seen the screenshot
- [x] 5. Last "Sign & Submit" item is disabled until all required fields are filled out. This item has a hover tooltip to explain why it's disabled (appears on hover of this item)

![image](https://user-images.githubusercontent.com/18424138/117223875-a6560e00-addc-11eb-83c4-a9891c508fba.png)

@caravinci  - here's the added notes about these icons and states:
![image](https://user-images.githubusercontent.com/18424138/118835251-d0093d80-b890-11eb-95ac-44109ba0c1c2.png)

**Comment by caravinci** [comment]
While I've completed implementation for this spec, this ticket is pending reviews/release of uikit changes (PRs linked to this ticket.)
Once those have been successfully published, I'll open a PR for this ticket, but will leave it out of the "in progress" column to better reflect that it's basically done.

Expected result upon deployment:
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/8fdb7e21-3023-49dc-a5c0-aeb87568200d)
Of note, the tooltip's position is not 1:1 with what's shown in the mock (i.e. at the end of the tab's label text), for it would potentially result in having a tooltip show to the left or even under the mouse pointer (strange behaviour for a tooltip) if the user hovers near the right edge of the tab; as well as this being a reusable component, other tabs with different label text lengths would have the tooltip at different X positions, which may look messy/inconsistent. 
If we wanted to customise the tooltip for this individual tab in this particular project, which is of course perfectly valid + possible, further work is required in the uikit's tooltip component due to dependency issues (not worth discussing in the scope of this here ticket).

**Comment by kcullion** [comment]
@caravinci this looks great to me!
@rosibaj do you want to have a quick look? Or can we close this ticket?
