### ISSUE TITLE
[UI]: Application Section: Introduction

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#16]
**Goal:** To build the introduction section with the agreement validation.

Zeplin: https://zpl.io/2y3AnAy

## Expected Outcomes
- [x] Set up all content with proper styles (section title, body content, form section headings, links). Note: content is TBD so I won't provide the link URLS yet. 
- [x] Form checkbox. This type of form element has already been built: https://argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcheckbox--default
- [x] Local validation for the required field should work.

![image](https://user-images.githubusercontent.com/18424138/117323531-f674b500-ae5c-11eb-90e2-a8928d6cb853.png)

**Comment by caravinci** [comment]
This ticket required the following scope extensions:

To enable local validation

1. Adds `focus` and `blur` functionalities to the UiKit Checkbox (handlers and styling), allowing to discern `pristine` vs `touched` vs `valid/invalid` statuses.
2. - Integrates UiKit Checkbox to FormControl, in order to allow passing "required" and "error messages" to encompass the `focus/blur` behaviour.
3. - Adds an "error message" alternative mode to FormHelperText (which can be used alongside the another such component in its original mode, e.g. https://argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcontrol--input).

Also sets the foundation for the application overall validation (without Back End integration yet), and adds query parametrisation (e.g. `url?section="introduction`), in order to enable consistent behaviour when switching sections, upon refreshing, and if users create bookmarks.

**Comment by caravinci** [comment]
Thought of disabling temporarily the need for logging in to see the application forms, while we develop the initial layouts and functionalities; as I wasn't able to make the login work while on localhost.

We may have to do so in order to test things ¯\_(ツ)_/¯

**Comment by kcullion** [comment]
@rosibaj @caravinci this section looks good to me!
