### ISSUE TITLE
Cover plus Sign and Submit Page 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#175]
- [x] Complete cover for pdf
- [x] Complete Sign and Submit page
- [x] missing colons on some vertical table headers, i.e. Applicant info. (as mentioned on https://github.com/icgc-argo/dac-ui/issues/128)
- [x] added lay summary to pdf

**Comment by anncatton** [comment]
@rosibaj I added the `summary` data in this pr

**Comment by kcullion** [comment]
Thanks @anncatton ! This is looking really great. Here's some preliminary style feedback...I will now try testing different content in the application that is now saveable. 

- [ ] we discussed the font changes over slack
- [ ] fix checkbox svgs (will send files over slack)
- [ ] uppercase for DACO
![image](https://user-images.githubusercontent.com/18424138/124967219-2aea2600-dff2-11eb-87a7-86454d57bed2.png)

- [ ] footer: `using` instead of `by`
![image](https://user-images.githubusercontent.com/18424138/124967307-448b6d80-dff2-11eb-9285-b4de4dbc4c00.png)

- [ ]

**Comment by kcullion** [comment]
This feedback will be tested with https://github.com/icgc-argo/dac-ui/issues/128

So this ticket looks good to me @anncatton and @rosibaj
