### ISSUE TITLE
Save Feedback 🐛 Title does not load 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#189]
https://drive.google.com/file/d/1s6qPyWcHZO0pMgYHL237ullKf7_N6rG-/view

- section is complete, title is just not loading into the dropdown component
- see video - section is complete bc data has title
- just the dropdown is not rendering the Dr --> it is staying at the Select option
## Expected behaviour
The dropdown should always render the saved title 
 
 For sections A and B

**Comment by caravinci** [comment]
As it turns out, the title can be saved if you change the value twice, so I've added an easy fix for that `touched` vs `pristine` logic.

However, troubleshooting this bug helped me notice there's another one with the Select component itself, in which the values can be sticky when the user switches back and forth between applicant and representative.
While I'm already queueing up a fix for that at UiKit, the package update can be added later on, as that newfound bug was not in the scope herein described.

**Comment by rosibaj** [comment]
tested Jul 13, 2021
- created a new application https://dac.qa.argo.cancercollaboratory.org/applications/DACO-95?section=representative 
- was able to add an applicant with title.  clicked away and back several times and the title reappeared
- was alos able to add title for iR.  persisted after logout/logback in so all looks good. 
Thank you @caravinci !
