### ISSUE TITLE
Save Feedback🐛 Cannot Add adddress for IR

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#190]
## Describe the bug
https://drive.google.com/file/d/1uxu0YzrBzwl9WBErUt-RuFT4Yb0tG_yN/view
## Steps To Reproduce
- https://dac.qa.argo.cancercollaboratory.org/applications/DACO-75 
- attempted to add address 
- data was constantly erased/ 

saw this error

## Expected behaviouR
Data I input into fields should not be erased.

**Comment by caravinci** [comment]
Seems the issue is caused by some business logic changes in the API, implementing the `addressSameAsApplicant` flag's functionality.
Any requests to change/add a representative's address data, while the flag is `true` will be ignored.

Desirable future enhancement: the API should respond with an error whenever that happens, to inform the a user of the invalid request, rather than just ignoring the changes with a `200` response. 
This will also help ensure correct handling from the UI.

**Comment by caravinci** [comment]
The API logic that prevented saving Representative address data seems to have been corrected. Moving across environments following API release cycle. No changes were necessary UI side at this time.

**Comment by rosibaj** [comment]
Tested Jul 13, 2021: 
- was able to add an IR without the applicant filled in 
- all fields saved as expected. 
- was abel to adjust fields as expected. 
-
