### ISSUE TITLE
[Data Hookup+UI] Admin Approval flow + Application state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#61]
## Goal
To complete the admin approval flow and transition the application to the correct state.

Note, the approval email that gets triggered will be built in the email epic here: https://github.com/icgc-argo/dac-ui/issues/68
(All emails to be built and triggered in this epic: https://github.com/icgc-argo/dac-ui/issues/65)

## Endpoint to use
https://github.com/icgc-argo/dac-api/issues/16

### Confirmation Modal
- [x] build the UI for the approval confirmation modal: When DACO Admin clicks the "Approve" button from https://github.com/icgc-argo/dac-ui/issues/55, they see this modal: https://zpl.io/VkMmDJG that loads in:
a. Application number and institution in brackets
b. Access start date (reporting the current day - i.e. the day this button is clicked)
c. Access end date (reporting one year after the start date)
![image](https://user-images.githubusercontent.com/18424138/120375010-445bcc00-c2e8-11eb-8c15-f57a29cdb1fe.png)

### Application state after approved 
- [x] 1. When confirm approval, the application transitions into the `APPROVED` state 
- [x] 2. Most sections are locked for editing as shown here for section A: https://zpl.io/aBvEw80
- [x] 3. For locked sections, all form fields are disabled and uneditable as seen here for section A: https://zpl.io/aBvEw80
- [x] 4. Section C is unlocked in order to be able to add/remove collaborators

![image](https://user-images.githubusercontent.com/18424138/120373207-11183d80-c2e6-11eb-9aaa-211efdc4aef2.png)

### Application state after approved for DACO Admin
- [x] Keep the orange bar and disable the buttons in this state. 

### Section C 
- [x] 6. Section C table: remove the edit icons from each collaborator table row, the applicant cannot edit already existing collaborator information. But they can still add and remove collaborators. Zeplin: https://zpl.io/2jq8pqp
![image](https://user-images.githubusercontent.com/18424138/120374273-5be68500-c2e7-11eb-8237-b7d7d3952756.png)

### Section E
will be hooked up in this ticket https://github.com/icgc-argo/dac-ui/issues/58

**Comment by samrichca** [comment]
Some work can't be completed right now because the following aren't implemented

- ethics section seeding
- uploading an ethics letter
- choosing whether to upload an ethics letter

- 5. Section E is locked if the applicant had chosen option 1 (do not require an ethics letter) and unlocked if the applicant had chosen option 2, that they require a letter.
-  7. If the applicant had chosen option 2 (required an ethics letter), show the ethics uploads that were originally submitted but hide the delete (trashcan) icons for those, as seen: https://zpl.io/beP4zMY
- 8. Disable option 1 (they cannot go from requires a letter to doesn't require a letter), as seen: https://zpl.io/beP4zMY
- 9. If the applicant uploads a new ethics pdf, that pdf is shown in the table and is removable, as seen: https://zpl.io/blOm11X

**Comment by kcullion** [comment]
Thanks @samrichca I'll move these items to a new ticket

**Comment by kcullion** [comment]
update: there was a ticket for it:https://github.com/icgc-argo/dac-ui/issues/58

**Comment by samrichca** [comment]
@kcullion even better! thanks for finding that

**Comment by kcullion** [comment]
@samrichca yes I"m glad you didn't waste time on that! forgot that I put that as part of your ticket

**Comment by rosibaj** [comment]
Tested Jul 12, 2021
- approval worked perfectly from frontend
- data rendered correctly in the modal  
- no bugs right now.

lgtm thank you @samrichca!!
