### ISSUE TITLE
Refresh bugs

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#81]
Loading/refresh bugs
- [x] when the page refreshes (or say navigating from an application back to dashboard), the header items flash: the logo flashes on and off, and the user items on the right flash to show the logged out state then logged in state
- [x] The footer ARGO logo flashes off and on which causes a weird relocation of the middle links.

**Comment by kcullion** [comment]
@rosibaj is there a way to add this loader in the system in general, not just for login?

**Comment by samrichca** [comment]
platform: SVGs render as base64, and they don't flash
daco: SVGs render as SVGs, causing a flash

it's not immediately apparent to me why that is, but that's my theory for why the layout continues to flash after being moved up as high in the app hierarchy as it can go.

**Comment by caravinci** [comment]
Thinking about this, I remember in another project the issue was with bundling the SVGs as part of the app's code (i.e. importing them into the component), rather than linking to the image, and letting the browser cache them.
While the problem may have been the other way around (linking instead of bundling), my point is playing with these ideas (plus some placeholding CSS) may prove a good enough solution.

**Comment by samrichca** [comment]
@caravinci we were linking in this case but the browser isn't caching. it was making network requests on every render

**Comment by rosibaj** [comment]
lgtm thank you @samrichca
